### ISSUE TITLE
look into BiocParallel

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#106]
the base parallel we are using have problems when file are read by multiple threads.

**Comment by lweasel** [comment]
Is this a problem that we are still seeing @hxin ? Or can we close this.

**Comment by hxin** [comment]
I think we can refactor to bioparrallel and I think that will be a better way than using the base parallel. However this will probably be a feature improvement rather than a bug as we are now limiting the number of parallel process, it will mostly like NOT went into this error.

**Comment by lweasel** [comment]
Righto, changed to an enhancement.
