### ISSUE TITLE
Force python virtual environment when running run_analysis.sh

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#108]
I wonder if it's worth adding a "workon virtual_environment" line to run_analysis.sh? This would then avoid the perennial problem of the get_gene_lengths script silently failing. 

I can't immediately think of a reason why you'd ever need to run run_analysis.sh and not be in the appropriate virtual environment. Let me know if you can think of any problems with this @hxin @katieemelianova

**Comment by hxin** [comment]
I can't think of any issue doing this. I will add a line in the run_analysis.sh, can reopen if it caused any issue.

**Comment by lweasel** [comment]
Not sure this is working?

`./run_analysis.sh: line 21: workon: command not found`

Do we need to set up virtualenvwrapper first like we do in `initial_setups.sh`?

```
export WORKON_HOME=${HOME}/.virtualenvs
export PROJECT_HOME=${HOME}/projects
source /usr/local/bin/virtualenvwrapper.sh
```
