### ISSUE TITLE
Add sample ordering question to cookiecutter

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#110]
It's always nice to impose some kind of ordering on the samples so that, e.g., the FPKM columns in the output spreadsheets are grouped together in some rational way (for example, all WT samples together, all KO samples together) - it makes the spreadsheet easier to read. This can be done manually by order SAMPLE_TABLE in meta_data.R by some combination of columns, but I wonder if we could add a question to cookiecutter setup to do this more automatically?

**Comment by lweasel** [comment]
Or perhaps this makes more sense as a variable to fill in in the meta_data.R script(s), like AVG_FPKM_GROUP. In fact, what might make even more sense, is to order the sample FPKM columns according to the first element of AVG_FPKM_GROUP.

**Comment by hxin** [comment]
The order of the fpkm columns depends on the counts columns, which is the same order as the SAMPLE_DATA. 

```
total_dds_data <- get_total_dds(SAMPLE_DATA, SPECIES, qSVA = qSVA, design_formula = ~1)
results <- total_dds_data %>% get_count_data()
fpkms <- results %>% get_fpkms(gene_lengths, colnames(results) %>% tail(-1), "_fpkm")
```


So should I just do a re-order base on the first element of the AVG_FPKM_GROUP right after the defining AVG_FPKM_GROUP variable?  something like below?
```
AVG_FPKM_GROUP <- list(c('condition'), c('condition','cell_tyep'))
SAMPLE_DATA %<>% arrange(AVG_FPKM_GROUP %>% unlist() %>% head(1))
```
@lweasel

**Comment by lweasel** [comment]
Yeah, I reckon do what you suggest at the end there - re-order SAMPLE_DATA based on the first element of AVG_FPKM_GROUP. You might also want to add a comment to suggest that it would be best for the user to make the first element of AVG_FPKM_GROUP the one with most factors (i.e. in the example you've shown, it would be best for the output file if the FPKM columns are ordered by condition, and cell_type within condition (i.e. the current 2nd element), rather than just condition (the current 1st element)
