### ISSUE TITLE
str_c used before stringr imported

### ISSUE THREAD

**Issue by katieemelianova** [sidbdri/cookiecutter-de_analysis_skeleton#113]
diff_expr_species.R uses str_r to infer name of metadata file, but requires metadata file to be run to use str_c (by running load_packages.R)

**Comment by hxin** [comment]
This has been fixed in master by [this](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/commit/92f4abf3f6659b1701cf0a68a5070ebb0b8df6db) commit.
