### ISSUE TITLE
Save CSV files containing data for PCA plots

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#115]
I've just realised that I've been asked on multiple occasions (including today) for adjustments to be made in terms of point size, text sizes, colours etc. etc. on PCA plots. I think that we could easily start writing out a CSV file for each PCA plot containing the co-ordinates of each point (and the relevant metadata), so that people could re-plot this data themselves.

**Comment by hxin** [comment]
I can save the object if that makes it easier?  Or do you mean to plot the PCA outside R?

The plotting code looks like this and I the _pca_data_ is a table as below. This can be written into a csv file somewhere.
```
plot_pca <- function(vst, intgroup=c("condition"), plot_label = TRUE, label_name='name', include_gene = c(),
                     removeBatchEffect = FALSE, batch = NULL){
  ...
  pca_data <- vst %>% plotPCA2(intgroup = intgroup, returnData = TRUE, include_gene = include_gene)
  ...
}

pca_data
                 PC1        PC2 group condition      name
09_37STG   -6.404284   4.559040   CON       CON  09_37STG
09_37VIS   10.597627   7.004399   CON       CON  09_37VIS
11_06STG   31.568449 -23.884327   CON       CON  11_06STG
11_06VIS   10.378547 -21.628948   CON       CON  11_06VIS
14_04STG   37.677937 -17.456728   CON       CON  14_04STG
14_04VIS   25.633190 -17.845795   CON       CON  14_04VIS
14_16STG   -5.613165  -6.539114   CON       CON  14_16STG
14_16VIS  -23.853595 -14.640052   CON       CON  14_16VIS
...
```

@lweasel

**Comment by lweasel** [comment]
Yeah, this would (potentially) be to plot the PCA outside of R. I reckon just save that table as a CSV file into the same folder that the graphs themselves go into.

**Comment by hxin** [comment]
Do we want to just save the main PCA plot, or ALL PCA plots including that done per-comparison?

**Comment by lweasel** [comment]
If it's not too much extra effort, may as well save all of them?

**Comment by hxin** [comment]
okay
