### ISSUE TITLE
Rename "go" and "gsa" folders

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#116]
It's mainly the "go" one that is causing _endless_ confusion (because the gsa folder also contains results for "GO" gene sets), and I'm weary of trying to explain it to people :-)

I'd perhaps suggest:

"go" -> "enrichment_tests"
"gsa" -> "gene_set_tests"

but I'm open to any suggestions.

**Comment by zkozic** [comment]
Modified this in the diff_expr.R.
