### ISSUE TITLE
bioconductor version error

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#117]
```R
source("https://bioconductor.org/biocLite.R")
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install

```

This in load_packages.R is giving error with R3.6

**Comment by lweasel** [comment]
I think that's already been fixed?

https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/f2a6b8083321672da451491ca7cf94f23453b879/%7B%7Bcookiecutter.project_name%7D%7D/load_packages.R#L27

**Comment by hxin** [comment]
ahhh, right I am running an older project... ok close!
