### ISSUE TITLE
Naming around PCA plot "features" is a bit confusing

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#118]
We have a PCA_FEATURE variable in the meta data script, which controls which which features will appear in the legend in the "main" PCA plot (e.g. "pca_all_mouse.pdf"). 

But we also have the, e.g., "pca_features_mouse.pdf" PCA plot, which has one plot per column in the SAMPLE_DATA table (except "species" and "sample_name"), plus a plot coloured by 5' to 3' read bias. But this "pca_features_mouse.pdf" plot doesn't have anything to do with the PCA_FEATURE variable, so this is a little bit confusing - we can just do a bit of renaming to clarify.

**Comment by hxin** [comment]
I think the per-comparison PCA plot every column in the SAMPLE_DATA table except the species and sample_name. This is also true for the 'pca_features_<species>' plot.

The PCA_FEATURE only control the 'pca_all_<species>' which is misleading.

You probably way better in naming these base on my previous experience :P 
I am fine with whatever you have in mind, otherwise, what do you think the following:
```
 pca_all_human.pdf -> pca_all_samples_human.pdf * this is what the PCA_FEATURE controls
 pca_features_human.pdf -> pca_all_features_all_samples_human.pdf
 pca_ftd_vs_con_age_filtered_human.pdf -> pca_all_feature_ftd_vs_con_age_filtered_human.pdf

```

**Comment by lweasel** [comment]
How about rename:

```
pca_all_human.pdf -> pca_all_samples_human.pdf
pca_features_human.pdf -> pca_all_features_all_samples_human.pdf
```

as you suggest, because this makes it clear that these two plots contain all samples, which is not true for the other PCA plots (and actually we could rename the "all" **heatmap** that includes all samples to include "all_samples" in the title as well). Leave the per comparison titles as they are I reckon.

But can we can we also rename "PCA_FEATURE" variable to make it clearer that this **doesn't** have anything to do with the "pca_all_features_all_samples_human.pdf" plot. Perhaps:

```
PCA_FEATURE -> FEATURES_FOR_ALL_SAMPLES_PCA
```

That's not a great name, but I think it's a bit clearer.
