### ISSUE TITLE
Rename column headers in GO results

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#119]
Was just writing an explanatory email about GO results and realised that some of the column headers are a bit confusing/misleading if you're not familiar with topGO. I'm thinking we could change these to something like:

Annotated -> annotated_in_background
Significant -> annotated_in_gene_set
Expected -> expected_annotated_in_gene_set
weight_fisher -> pvalue

Happy to hear other suggestions though!

**Comment by zkozic** [comment]
Changed this in the common_function.R.
