### ISSUE TITLE
Fully replicate parallel processing of pipeline

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#121]
In the current pipeline, there's a hand-rolled parallel processing implementation which uses NUM_THREADS_PER_SAMPLE (maximum number of threads to be used by any one process), NUM_TOTAL_THREADS (maximum number of threads to be used in total) and "xargs". I think we should be able to fully replicate this using the "threads" parameter in the snakemake rules, and the --cores option to snakemake itself. Basically any part of the pipeline which uses xargs in the old script should hopefully be parallelisable in the new pipeline.

However, I suggest we address this after everything is definitely working in the case where everything is processed serially.

**Comment by katieemelianova** [comment]
fixed in  commit 48a3d3887fb7322a67cf0ae8bbe30ce096833600
