### ISSUE TITLE
Rename featureCounts strand test summary files on snakemake branch

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#132]
When we're testing the strandedness of our data by running featureCounts with strand=0,1,2, the summary files need to be named something other than ending with ".summary" (e.g. on the main line, they're called "*.testsummary"). The reason for this is that MultiQC's featureCounts module looks for files ending with ".summary", and so will pick up the summary files for the strandedness test and randomly overwrite (in the MultiQC output) the results for the tested sample with one of the test summary files.

**Comment by katieemelianova** [comment]
Whoops not fixed yet :)

**Comment by katieemelianova** [comment]
Okay now its fixed :)
