### ISSUE TITLE
plyr and dplyr collision 

### ISSUE THREAD

**Issue by katieemelianova** [sidbdri/cookiecutter-de_analysis_skeleton#133]
The summarise function in .get_avg_fpkm_table within common_functions.R has a call to summarise. This should be dplyr::summarise otherwise it doesnt work. (Putting this up for reference so I dint forget the next time this happens 👹)

**Comment by lweasel** [comment]
I wonder if we might want to start using this package:

https://cran.r-project.org/web/packages/conflicted/index.html

because it makes all collisions between methods an explicit error. I think we've hit enough of these problems now that it could be worth it!

**Comment by katieemelianova** [comment]
Ooh yes good idea - definitely would save a lot of time (and tears)
