### ISSUE TITLE
bic version dplyr namespace conflict 

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#136]

**Comment by hxin** [comment]
#135
#133

**Comment by hxin** [comment]
> Qn (which doesn't need any immediate response!): at some point I accidentally/deliberately updated my Bioconductor version locally, so that I have a different version than we have in Docker. This is making my life a living hell (e.g. I just found that dplyr arrange() behaviour with respect to upper and lower case has changed). At some point that is convenient for everyone, I wonder if we can consider updating both our local installations, and Docker, to the latest version of Bioconductor?

**Comment by hxin** [comment]
can use this for testing https://github.com/sidbdri/nrf2_astrocytes_lps_jing

**Comment by lweasel** [comment]
p.s. #135 is a "row names" bug, rather than a namespace clash. 

There may be additional new problems in Bic 3.12 (which has only just come out), but I reckon we may as well move to the latest.

**Comment by hxin** [comment]
> p.s. #135 is a "row names" bug, rather than a namespace clash.
> 
> There may be additional new problems in Bic 3.12 (which has only just come out), but I reckon we may as well move to the latest.

yeah agree go latest so we will be good for a while...

**Comment by katieemelianova** [comment]
Is this an issue to keep track of other issues? Or can it be resolved once #135 and #133 are fixed?

**Comment by lweasel** [comment]
I think it can be resolved.

**Comment by katieemelianova** [comment]
Closing this issue because the issues contained within it are waiting for merge now ✌️
