### ISSUE TITLE
Remove redundant strand test calculations

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#137]
If I'm understanding correctly, every time that we need to know the strandedness of the data (e.g. each time that we run picard or calculate the read counts for a sample), we need to recalculate this by re-running featureCounts three times, which is a bit slow. I don't know how to do this in snakemake, but can we store this value in a file the first time it is calculated instead?

**Comment by katieemelianova** [comment]
Now featurecounts only run once and stored in a global variable, see ce3234a39bf28df4db31b6780098f5c16b017feb
