### ISSUE TITLE
Shared single- and multi-species snakemake code?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#138]
Is it possible to share code between Snakemake files? We have targets which (I think!) should be the same between the multi- and single-species cases. Having to maintain two copies of sich code is likely to introduce inconsistencies.

**Comment by katieemelianova** [comment]
Yep good idea, should just be able to do a snakemake include directive on all shared modules etc :)

**Comment by katieemelianova** [comment]
fixed in 6b05e243f86cdf1a4a97b6965298527397ae5b37 and previous commits
