### ISSUE TITLE
qSVA preparatory code doesn't work in Docker

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#139]
Because the region_matrix.py code (which is very old) doesn't work in Python 3.

**Comment by hxin** [comment]
The qSVA we are using is from [here](https://github.com/nellore/region_matrix), it [only supports](https://github.com/nellore/region_matrix/blob/master/README.md) python 2.x

I guess we can either:
- swap to the above mentioned R equivalent, not sure how this will works out 
 I just did a few searches and found [this](https://bioconductor.org/packages/release/bioc/html/sva.html) (see [ref](https://pubmed.ncbi.nlm.nih.gov/28634288/))
- or change nothing but call python2 specifically when doing qSAVE, i.e
    `python2 /opt/region_matrix/./region_matrix.py`

This is just to confirm that python2 works in the VE in docker (I used the docker container that you created just now for the FLTD project to test it out, hence it's your username)
![image](https://user-images.githubusercontent.com/3407502/104738238-2b89ba00-573d-11eb-9410-f0be0193645c.png)

I prefer the latter though...

**Comment by hxin** [comment]
The latter also does not require any change in docker, as we can hardcode the _python2_ in the run_analysis.sh script instead.

**Comment by lweasel** [comment]
Yeah, hardcding python2 is probably easiest, isn't it. That's what I just did in the current container to get it to work.

**Comment by hxin** [comment]
Okay i will create a fix later today

**Comment by hxin** [comment]
I can't find the qsva code in the dev branch which was in master [here](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/c101c75887267fe0f93fb6e175419e01b16e94a4/%7B%7Bcookiecutter.project_name%7D%7D/run_analysis.sh#L223). Anyone can point me where it is? @lweasel @katieemelianova

**Comment by lweasel** [comment]
May need to re-add it again, in snakemake style.
