### ISSUE TITLE
Check for invalid comparison names?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#142]
I just hit some errors in the R script due to having specified comparison names beginning with a number. Because it wasn't obvious that this was the problem, could we add an up-front check for comparison names beginning with an illegal character?

**Comment by hxin** [comment]
I think this is an R issue if you remember that I added that strange 'X' in the glucose project cause those 2CC,50CC starting with number. I will add a function to check this after the comparison table.
