### ISSUE TITLE
Problem with return value of get_misassignment_percentages()

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#143]
Am very confused!

get_misassignment_percentages() is returning a vector with named elements. But the code that calls it (in diff_expr.R) is trying to access these elements in a way which doesn't work for vectors. So this code fails - or am I totally misunderstanding?

**Comment by hxin** [comment]
hmmm am I being delutional I thought 
```R
ret <- {}
```
the same as 
```R 
ret<-list()
```
but apparently not. I am so confused now how that pervious project works with this???

**Comment by lweasel** [comment]
Me too!

**Comment by hxin** [comment]
The BBB project has this code base on this:
https://www.dropbox.com/sh/sf5hwrd3azmv33x/AADlO8z4GYofT0ckOTd6Kprda?dl=0&preview=sessionInfo.txt

the commit used in that project shows here:
https://github.com/sidbdri/bbb_pbaxter/blob/6d62ddf2fc552b45f294bf77c4cdee4345a613de/diff_expr_human.R#L106
https://github.com/sidbdri/bbb_pbaxter/blob/6d62ddf2fc552b45f294bf77c4cdee4345a613de/common_functions.R#L1636

What?

**Comment by hxin** [comment]
I just use the sessionInfo and recreate that container, I got into R and the '{}' did not work!

**Comment by lweasel** [comment]
Is it an R version thing? (Though that seems unlikely).

It's easy enough to fix, I guess, but very puzzling as to why it is happening.

**Comment by hxin** [comment]
yeah I will fix it now but I AM SO CONFUSED WHY IT WORKED BEFORE?!

**Comment by lweasel** [comment]
Also, somehow, I think that this bug only showed up when _only some_ of the comparisons have entries in the MISASSIGNMENT_SAMPLE_REFERENCE_TABLE table.
