### ISSUE TITLE
naming conflicts between sargasso/single-species run 

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#145]
```
xinhe@sidbdri:~/Projects/snakemake_single$ ls -l results/final_bams/
total 4172
lrwxrwxrwx 1 xinhe xinhe      26 Feb  1 02:20 1467_A.rat.bam -> ../mapped_reads/1467_A.bam
-rw-rw-r-- 1 xinhe xinhe   66328 Feb  1 02:20 1467_A.rat.sorted.bam
-rw-rw-r-- 1 xinhe xinhe 1343456 Feb  1 02:20 1467_A.rat.sorted.bam.bai
lrwxrwxrwx 1 xinhe xinhe      26 Feb  1 02:20 1467_V.rat.bam -> ../mapped_reads/1467_V.bam
-rw-rw-r-- 1 xinhe xinhe   68714 Feb  1 02:20 1467_V.rat.sorted.bam
-rw-rw-r-- 1 xinhe xinhe 1358424 Feb  1 02:20 1467_V.rat.sorted.bam.bai
lrwxrwxrwx 1 xinhe xinhe      26 Feb  1 02:20 1468_P.rat.bam -> ../mapped_reads/1468_P.bam
-rw-rw-r-- 1 xinhe xinhe   67315 Feb  1 02:20 1468_P.rat.sorted.bam
-rw-rw-r-- 1 xinhe xinhe 1359224 Feb  1 02:20 1468_P.rat.sorted.bam.bai
```

In multi-species case, the sorting happen in sargaaso, thus the bam file({sample}.{species}.bam) in the final_bam folder is already sorted. 

In the single-species case, the sorting created another file named {sample}.{species}_sorted.bam file. This breaks the code trying to access the indexed bam file using the naming convention {sample}.{species}.bam(without the 'sorted').

Example:
```
rule run_qsva:
    input:
        bam = "results/final_bams/{sample}.{species}.bam"
    output:
        qsva_out = "results/read_counts/{sample}.{species}.dm.tsv"
    params:
        region_matrix_executable = "/opt/region_matrix/region_matrix.py",
        regions = "/opt/region_matrix/sorted_polyA_degradation_regions_v2.bed",
        wiggletools = "/usr/local/bin/wiggletools"
    shell:
        """
        python {params.region_matrix_executable} --regions {params.regions} --bams {input.bam} --wiggletools {params.wiggletools} > {output.qsva_out}
        """
```

qsva required indexed bam file in the format of 
"results/final_bams/{sample}.{species}.bam", which will not work for single species case due to the 'sorted' in the file name.

**Comment by lweasel** [comment]
I think things might have got a bit mixed up here in the snakemake transition (or I am confused, always likely).

What I understood the original (main line) behaviour was the following:
- We want the input to featureCounts to be _co-ordinate sorted_ BAM files.
- For single-species case, the call to STAR automatically creates co-ordinate sorted BAM files in the mapped_reads directory. These have "sorted" in the title. We make links to these sorted BAM files from the final_bams directory, but the links do not have "sorted" in the title.
- For the multi-species case, the output of Sargasso is _name_ sorted BAM files. Hence we need to make an extra call to "sambamba sort" to turn these into co-ordinate sorted BAM files. These co-ordinate sorted BAM files are output into the final_bams directory, withouth "sorted" in the title.
- Hence in both cases, we end up with BAM files in the final_bams directory which are co-ordinate sorted, but do not have "sorted" in the title.

So I think things might be the wrong way round on the dev branch? We don't need to explicitly sort in the single-species case (STAR already does it). We do need to sort in the Sargasso case (Sargasso outputs BAM files with the wrong type of sorting for featureCounts). There shouldn't be _any_ files with "sorted" in the name in the final_bams directory.

(I think).

**Comment by katieemelianova** [comment]
Oooh whoops - yeah sorry I must have got a bit mixed up! Will check it out!

**Comment by hxin** [comment]
we do have [this](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/84c7ad4283e820aef43bdcf3b6c0769c2a783c87/%7B%7Bcookiecutter.project_name%7D%7D/Snakefile.multispecies_analysis#L41) in the current dev branch which cord-sorts the sargasso output bam into the final_bam folder. I think this is correct.

For the single-species case, we have [this](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/84c7ad4283e820aef43bdcf3b6c0769c2a783c87/%7B%7Bcookiecutter.project_name%7D%7D/Snakefile.singlespecies_analysis#L27) in the dev branch, which is a reimplement of the master version of [this](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/c101c75887267fe0f93fb6e175419e01b16e94a4/%7B%7Bcookiecutter.project_name%7D%7D/functions.sh#L45).  I will just have to link the 'sorted' bam file to the final_bam folder and index them.

Please check again #146 and see if this looks right? @lweasel
