### ISSUE TITLE
STAR parameter only handle paired end reads

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#147]
https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/5231bea577cc928181aa467b2844524144a24cb8/%7B%7Bcookiecutter.project_name%7D%7D/Snakefile.singlespecies_analysis#L25

I think here STAR only works for paired-end reads? The code will fail for single-end reads (i.e only 1 fastq file provided) because the __reverse_reads__ does not exist? I hit this error when running the test in docker with a recent [project](https://github.com/sidbdri/microglia_stroke_ckirby/tree/test_docker) 

@katieemelianova @lweasel

**Comment by katieemelianova** [comment]
For single end reads, cookiecutter should be filled in with the Forward read suffix and the reverse read suffix should be left as *. when it greps, if it doesnt find the reverse reads then it returns an empty string, so the star command just has the forward reads and an empty string where reverse reads would be.

I ran it on single end reads the other day, though if you've seen behaviour where it doesn't work could you let me know please?

**Comment by hxin** [comment]
hmmm thanks @katieemelianova  I double-checked and think the error was due to not finding the forward reads because the read name. The reverse read logic is correct as you said.

The fastq file name is like this:
`data/rnaseq/Sample_101/Sample_101_R1_merged.fastq.gz`

The pattern I used is:
`R1`

Thus the following returns empty line
`ls data/rnaseq/Sample_101/Sample_101_R1_merged.fastq.gz | grep R1'.fastq.gz' || printf ' ' `

I think the following might work for the case where the pattern is not directly followed by the fastq.gz:
`ls data/rnaseq/Sample_101/Sample_101_R1_merged.fastq.gz | grep R1.*'.fastq.gz'|| printf ' '`

**Comment by katieemelianova** [comment]
Yep - you'll have to include the 'merged' part of the filename for it to construct the fastq path correctly.
It may be helpful in future to run the snakemake command this failed on also using the -np flag - this tells it to not run the actual commands and to also print out the commands it will execute - helpful for testing individual commands and debugging! 👌

**Comment by hxin** [comment]
Ahhh great thanks for the -np I was digging out log to find that bash command xd

**Comment by hxin** [comment]
nothing need to be fix for now. Just need to remember when entering the read identifier, it needs to be everything all the way till the __.fastq.gz__

**Comment by katieemelianova** [comment]
No that's not correct. The cookiecutter setup works exactly as before. The .fastq.gz bit is the fastq_suffix, the read identified needs to be whatever the format is of the reads.

**Comment by hxin** [comment]
Yes, it is. I was confused and thought that I can enter just the identifier like __R1/R2__ in the below case when I should enter ___R1_merged./R2_merged___ instead.  There is nothing wrong with the code, and the code behaves exactly the same as before.
``
Sample_117_R1_merged.fastq.gz
Sample_117_R2_merged.fastq.gz
```
