### ISSUE TITLE
project_setup.sh not recording the correct version of packages

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#149]
https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/39284f3f3f79eee34e49217a1191553b77fdfdb7/%7B%7Bcookiecutter.project_name%7D%7D/project_setup.sh#L19

I am so confused with this line.  I can't remember why I put -F in it but that's not a problem, however, the -q silence the __grep__ output so it will always print out nothing. If the output is nothing, it will never go into the bit of code that init the hash, so HOW IS THIS WORKED IN THE PAST?????? @lweasel 

```
#worked
echo "transcript_utils_hash=unknown_hash_transcript-utils
sidbdri_utils_hash=unknown_hash_sidbdri-utils
sargasso_hash=unknown_hash_sargasso" | grep "unknown_hash"

#doesn't work
echo "transcript_utils_hash=unknown_hash_transcript-utils
sidbdri_utils_hash=unknown_hash_sidbdri-utils
sargasso_hash=unknown_hash_sargasso" | grep -Fq "unknown_hash"


```

**Comment by lweasel** [comment]
Isn't that code checking the _exit status_ of the grep command? i.e. if "unknown_hash" is present in the file, then the exit code is zero (=true for the purposes of the if statement), and the code goes into the part which inits the hash. If "unknown_hash" is not present, the exit code is 1 (=false), and we don't go into the hash initiation code.

Seems to be doing the right thing to me?

**Comment by lweasel** [comment]
Think we agreed this code is ok.
