### ISSUE TITLE
use post-hook to record project setup parameter

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#151]
We want to be able to re-create the project using cookie-cutter with the init parameter.

This can be done using [post-hook](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/hooks.html)

**Comment by hxin** [comment]
It seems that the dictionary parameter cannot be passed via the command line...?

**Comment by hxin** [comment]
so there are a few approach for this I guess...

- this is actually a new [feature](https://github.com/cookiecutter/cookiecutter/pull/906) which was implemented in May 2020, it was planned to be in the v2.0 release but yet to come... this will basically allow providing a .json file and which you can create by adding something like ```{{ cookiecutter | jsonify }}```

- we can use what is currently available, ```--replay``` option, which will read the json, but this might be a be tricky to implement. see [1.1.89 on page 21](https://buildmedia.readthedocs.org/media/pdf/cookiecutter/latest/cookiecutter.pdf) 

- we can use the [python version](https://cookiecutter.readthedocs.io/en/1.7.0/cookiecutter.html#module-cookiecutter.prompt) of the cookie-cutter, which accept the dictionary parameter. Something like below:

```python
from cookiecutter.main import cookiecutter
cookiecutter('/home/xinhe/Projects/cookiecutter-de_analysis_skeleton',
             no_input=True,
             extra_context={
                 "project_name": 'name',
                 "projects_base": 'Projects',
                 "gtf_files": {
                     "mouse": "Mus_musculus.GRCm38.95.gtf",
                     "human": "Homo_sapiens.GRCh38.95.gtf",
                     "rat": "Rattus_norvegicus.Rnor_6.0.95.gtf"
                 }
             })
```

Since this is a new feature already in the cookie-cutter master branch, should we update cookie-cutter to use this, or should we try the python approach which a similar task? @lweasel

**Comment by lweasel** [comment]
So weirdly, although I couldn't actually find it in the documentation, it seems that you _can_ supply extra context on the command line, e.g.,

```
> cookiecutter https://github.com/sidbdri/cookiecutter-de_analysis_skeleton
You've cloned /home/odando/.cookiecutters/cookiecutter-de_analysis_skeleton before. Is it okay to delete and re-clone it? [yes]: 
project_name [newproject]
```

but...

```
cookiecutter https://github.com/sidbdri/cookiecutter-de_analysis_skeleton project_name=hello
You've cloned /home/odando/.cookiecutters/cookiecutter-de_analysis_skeleton before. Is it okay to delete and re-clone it? [yes]: 
project_name [hello]:
```

So, perhaps we could use a post-hook to take a JSON file that has been created with `{{ cookiecutter | jsonify }}` and turn it into a command with all the option choices as these ```key=value``` pairs (and record that command in a bash script)? What do you think @hxin ?

**Comment by hxin** [comment]
yes you can provide extra context in commandline options but I don't think it is possible to pass those dictionary parameter in commandlline, 
i.e
you WON'T be able to do this:
cookiecutter https://github.com/sidbdri/cookiecutter-de_analysis_skeleton gtf_files= {
                     "mouse": "Mus_musculus.GRCm38.95.gtf",
                     "human": "Homo_sapiens.GRCh38.95.gtf",
                     "rat": "Rattus_norvegicus.Rnor_6.0.95.gtf"
                 }

**Comment by lweasel** [comment]
Oh, right, sorry - I understand now. Hmm.

**Comment by lweasel** [comment]
However @hxin ...I can't remember a time when I've actually changed any of those dictionary parameters, I pretty much always use the defaults (which themselves depend on the Ensembl version). Could we get 90% of the way there by just creating a command which passes in the non-dictionary parameters?

**Comment by hxin** [comment]
yes 
- for all non-dict parameter we can create bash command to repeat it.
- for the dict parameter, we can use a python approach to rerun it rather than a bash command
OR we can try the --replay-file with the new master cookiecutter.

**Comment by lweasel** [comment]
Shall we not worry about the dict parameters for now? I think we can get nearly all the useful functionality from creating a bash command for the non-dict parameters.

**Comment by hxin** [comment]
we can use the python way to re-create the project tho, which can handle the dictionary parameter?

**Comment by lweasel** [comment]
✔️
