### ISSUE TITLE
Pre-calculate Camera gene sets for mouse and rat

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#157]
To get the gene sets for Camera analysis for non-human species, we have to translate the human Entrez IDs in msigdb to the relevant species. We do this every time the differential expression script is run, and it takes *absolutely* ages. We could instead pre-calculate this information each time we do a new Ensembl download (i.e. using the latest set of Entrez ID mappings between species).

**Comment by hxin** [comment]
we in this case will be duplicating the code that map human-nonhuman from cookie-cutter into sidb-utli, or do we want to run mapping once per project rather then re-use within the project?

**Comment by hxin** [comment]
@lweasel

**Comment by lweasel** [comment]
I think we should move the code that maps human->non-human to sidb-utils. sidb-utils can then write this info out in a form that can easily be read by each individual project. Then we're only running the mapping once for each ensembl version / species combination. Sound reasonable?

**Comment by hxin** [comment]
yeah sure, are we using that mapping code anywhere else? I mean do we want
to keep a copy of those code in the project as well?

**Comment by lweasel** [comment]
I don't believe we use it anywhere else with the project.

**Comment by lweasel** [comment]
Create a branch off dev for the fix, will merge next time we download from Ensembl.

**Comment by hxin** [comment]
[ensembl 105 ](https://www.ensembl.info/category/01-release/) was release on 10th Dec 2021. 
We might want to test this code in https://github.com/sidbdri/sidbdri-utils/issues/11 as well as the next project using ensemble 105. 

NOTE: The code in sidbdri-utils has been committed to master, but the code in cookie-cutter has not. 
@lweasel
