### ISSUE TITLE
Errors(?) when running a project in Docker

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#159]
When running a project in Docker I see the following errors in the logs (highlighted in bold):

<code>
Installing collected packages: transcript-utils

Successfully installed transcript-utils-1.0.0

Cloning into 'sidbdri-utils'...

**/home/odando/.virtualenvs/nrf2_ert_myeloid_microglia/bin/python: Error while finding module specification for 'virtu
alenvwrapper.hook_loader' (ModuleNotFoundError: No module named 'virtualenvwrapper')**

**virtualenvwrapper.sh: There was a problem running the initialization hooks.**

**If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for**

**VIRTUALENVWRAPPER_PYTHON=/home/odando/.virtualenvs/nrf2_ert_myeloid_microglia/bin/python and that PATH is
set properly.**

**/home/odando/.virtualenvs/nrf2_ert_myeloid_microglia/bin/python: Error while finding module specification for 'virtu
alenvwrapper.hook_loader' (ModuleNotFoundError: No module named 'virtualenvwrapper')**

**/home/odando/.virtualenvs/nrf2_ert_myeloid_microglia/bin/python: Error while finding module specification for 'virtu
alenvwrapper.hook_loader' (ModuleNotFoundError: No module named 'virtualenvwrapper')**

Running get_gene_lengths for species ....

Building DAG of jobs...
</code>

(what you are seeing here is - I think - the end of initial_setup.sh, and the start of run_analysis.sh). I don't seem to get these errors if I execute run_analysis.sh manually. And I'm not sure that they're causing any actual problem - but do we have any idea why we're getting them?

**Comment by hxin** [comment]
When at the beginning of run_analysis.sh script we do 
`source /usr/local/bin/virtualenvwrapper.sh`
We however at the point is already in VE, and the $VIRTUALENVWRAPPER_PYTHON was somehow set to empty, thus this is going to somehow call the VE python executable which does not have the virtualen module installed. 

A hack for now I think would be to explicitly set the VIRTUALENVWRAPPER_PYTHON to point to the python OUTSIDE the VE, which is the system python that has the virtualen installed.

`VIRTUALENVWRAPPER_PYTHON=/usr/bin/python`



to repeat the bug, in a container:
```bash
source /usr/local/bin/virtualenvwrapper.sh
mkproject -f -p python3.8 test_bug
echo $VIRTUALENVWRAPPER_PYTHON
#/usr/bin/python


#error
export VIRTUALENVWRAPPER_PYTHON=''
source /usr/local/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=$(which python3)
source /usr/local/bin/virtualenvwrapper.sh

#fix
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/local/bin/virtualenvwrapper.sh
```

**Comment by hxin** [comment]
on sidb the system default python is pointing to python2.7, thus we need to hardcode the path to point t python3.8, instead of just python.
`export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.8`
