### ISSUE TITLE
Zip up gene set analysis heatmaps

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#175]
The new gene set analysis heatmaps are great. But in cases where there are large differences between conditions, the sheer number of significant gene sets for which we are producing PDFs is causing a problem for uploading the results sets to Dropbox. We could think about zipping up the folders containing the PDFs, either as part of the analysis run, or in the script (in sidbdri-utils) that is used to package up the results for delivery.

**Comment by hxin** [comment]
Should we zip the 'gene_set_tests' folder as a whole, which I think will make unzip as well then zip all the folders containing the pdfs?
In fact on top of this, I can even make an overall zip of the docker outcome if that makes it easier for upload/download?
@lweasel

**Comment by lweasel** [comment]
Ah right, actually you've made me think there is a better way of doing this. Yes, essentially we might want to zip up the whole set of results, but the thing is, I fiddle about with the structure a bit before sending them to people - so it might be better to do this as part of that process. Let me have a bit more of a think about this?

**Comment by hxin** [comment]
sure, I can do a zip on the graph folder along, and if we want to do a bit of re-arrange and more zips, that can also be done. I originally think I can write the zip code in run_analysis, but if we are going to re-organize the whole result structure, this might be more suitable to be in the docker utility script I think?
