### ISSUE TITLE
Sargasso project is not using enough cores

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#177]
https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/15eeba969a988301afb83e2ca1c950dc8ea4c02c/%7B%7Bcookiecutter.project_name%7D%7D/Snakefile.multispecies_analysis#L20

Sargasso only runs 1 sample at a time, thus we might want to change this to use NUM_TOTAL_THREADS instead.

**Comment by lweasel** [comment]
I don't think that this variable gets set.
