### ISSUE TITLE
cookiecutter pipeline integration test

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#185]
A separator [repo](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton_test) has been create which act as an  'integration test' of our cookiecutter pipeline.

A brief description can be found [here](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton_test/blob/main/README.md)

**Comment by hxin** [comment]
first implementation at  https://github.com/sidbdri/cookiecutter-de_analysis_skeleton_test/commit/6cf41f259fc82adcc7679d673d618bd672be9003

**Comment by arfinator** [comment]
Links are broken @hxin
