### ISSUE TITLE
check_formulas() doesn't work for interaction comparisons?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#190]
I think? I get errors like:

```
 Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'unique': Can't extract columns that don't exist.
x Column `media:treatment` doesn't exist. 
```

Any thoughts @hxin ?

**Comment by hxin** [comment]
let me check I don't think I have  use that function for interaction before.

**Comment by lweasel** [comment]
New repo https://github.com/sidbdri/ab_cortical_neurons contains some interactions, if you want to check (I've commented out the check_formulas() call.
