### ISSUE TITLE
Add check for empty genes.tsv

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#202]
Was just setting up an instance of the pipeline with @deepalivasoya, and we had execution errors late in the `diff_expr.R` script that turned out to be due to an empty `genes.tsv` file – I think that perhaps there was an intermittent failure in the internet connection between sidbdri and the outside world, that caused the download of this file from Ensembl to fail?

Could we perhaps add a check into `initial_setup.sh` to ensure that this file isn't empty after the attempt to download (and possibly re-attempt to download if there was a failure – though repeated failures should cause the script to exit with an error message?).

What do you think @hxin ?

**Comment by hxin** [comment]
The download function is at [here](https://github.com/sidbdri/sidbdri-utils/blob/435aa6b22341a5610b529470641aee67ceb3994b/src/ensembl_utils.sh#L204).

I think it might be easier to have a check in the project script than in the sidbdri-utils function.
I will look into fail/re-try methods in cookiecutter and see how it works out.
