### ISSUE TITLE
Slight inconsistency in naming of tx-level results files

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#204]
For gene-level DE, we have (e.g.):

`de_summary_<species>.csv`
`deseq2_results_fpkm_<species>.csv`

for the main files, and:

`<group_name>_de_summary_<species>.csv`
`<group_name>_deseq2_results_fpkm_<species>.csv`

when we're output subsets of comparisons.

For the transcript-level files, however, we have:

`de_summary_<species>.csv`
`deseq2_results_tpm_<species>.csv`

for the main files, but:

`<group_name>_de_summary_<species>_tx_salmon.csv`
`<group_name>_deseq2_results_tpm_<species>_tx_salmon.csv`

when we're output subsets of comparisons - i.e. for the subset files, there's an extra "_tx_salmon" on the end of the file name. I think we can remove this (it was probably initially for distinguishing between Salmon and Kallisto results).

**Comment by hxin** [comment]
tested
<img width="270" alt="image" src="https://user-images.githubusercontent.com/3407502/193643242-cf713e87-131d-42e4-bc51-5d9c71b00aad.png">
