### ISSUE TITLE
Problem plotting gene expression heatmaps

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#217]
In the following code in diff_expr.R:

```
## Plot gene expression heatmap for each comparison

start_plot("gene_expression_heatmap")
for(comparison_name in COMPARISON_TABLE %>% pull(comparison)) {
  plot_expression_heatmap(comparison_name = comparison_name,top = 50) %>%
    ComplexHeatmap::draw(column_title=comparison_name,column_title_gp=grid::gpar(fontsize=16))
}
end_plot()
```

shouldn't the start_plot() and end_plot() calls be inside the for loop, with a different string passed to start_plot() each time?

**Comment by hxin** [comment]
I think if wrap the start/stop outside, all the plots will end up in one pdf with each page containing one plot with the comparison name. We can change it so that it produces for each comparison a plot instead?

**Comment by lweasel** [comment]
Yep, I think that would probably be the thing to do.

**Comment by hxin** [comment]
okay, will change it so it produces one plot for each comparison in a separator file.

**Comment by lweasel** [comment]
(Sorry of course if I previously said the opposite to this!)
