### ISSUE TITLE
plot_expression_heatmap() broken by duplicate gene names

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#218]
Unfortunately, due to annotation errors, our genes.tsv file sometimes contains more than one gene with the same name. If they both appear in the set of genes to be plotted by plot_expression_heatmap(), then the code breaks because the heatmap doesn't allow duplicate gene names. 

A quick and dirty fixed would be something like:

```
# deal with potential duplicate gene names
  results_tb %<>% group_by(gene_name) %>% slice_head(n = 1) %>% ungroup() 
```

but there's probably a better way.

**Comment by hxin** [comment]
so they are two different gene with the same gene name?

**Comment by lweasel** [comment]
Well...yes, in the annotations there are two different Ensembl IDs which have the same gene name. This is most likely a mistake in the annotations (some of which are produced computationally, not by hand) - i.e. for the one particular one that I looked at, it had been fixed in the latest version of Ensembl. i.e. now it is two different Ensembl IDs with two different gene names.

p.s. code I gave above doesn't quite work cos it messes up the ordering of the heatmap, would need to be something like:

```
results_tb %<>% group_by(gene_name) %>% slice_head(n = 1) %>% ungroup()  %>% 
  arrange(desc(abs(!!sym(paste0(comparison_name, '.l2fc')))))
```

**Comment by hxin** [comment]
I see, I can either use gene_name to search and then use gene_name_ensembl_id as the plot so it will plot 2 heatmap in this case? Or I just take the random first one?

**Comment by lweasel** [comment]
I think we can just take a random first one. The plot is giving an "overall impression" of the differential expression comparison, so I don't think it really matters to spend too much time worrying about which is the "best" of the two genes in the odd cases like this.

**Comment by hxin** [comment]
I can add a check to take the higher expression one if that helps?

**Comment by lweasel** [comment]
Yep, that's a good idea if it's not too difficult.
