### ISSUE TITLE
Moving plots for improved understandibility

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#219]
When there are a lot of comparisons, navigating the "graphs" directory becomes a bit painful. I wonder if we might put plots that are specific to one particular comparison (there are quite of few of these now) in separate per-comparison sub-directories?

**Comment by hxin** [comment]
Can do this, or group the plot into one file per comparison, whichever you
think is easier to navigate.

**Comment by lweasel** [comment]
I think I would prefer folders, and keep just one plot per file.
