### ISSUE TITLE
Check for illegal characters in comparison names

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#221]
@zkozic and I found today that certain characters in comparison names (e.g. "-", ":") will cause obscure bugs later on when ggplot tries to use them as column names. We could check for these and fail early.

**Comment by hxin** [comment]
we do have code to check the comparison name but only giving out warnings
https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/73528f6d85cf86bf5c29a1d729416245aff2ab6e/%7B%7Bcookiecutter.project_name%7D%7D/meta_data_functions.R#L78

I can add ":" to the check and make it an error to stop the script if that make more sense? @lweasel

**Comment by lweasel** [comment]
Yeah, I think the script should stop if it encounters any of "+"/"-"/":", because it will inevitably cause errors later on.

**Comment by hxin** [comment]
grepl('[+-:]', x = '1P', perl = T) returns TRUE?
