### ISSUE TITLE
Remove "NA" section from plot_expression_heatmap() plots

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#224]
[gene_expression_heatmap_P31_Ola_vs_WT_mouse.pdf](https://github.com/user-attachments/files/16599867/gene_expression_heatmap_P31_Ola_vs_WT_mouse.pdf)

These plots are great, but we should remove the "NA" section, which contains genes for which a l2fc isn't calculated.

p.s. plot_expression_heatmap() seems to run quite slowly for some reason - can we check if this is still the case after removing the NA section?

**Comment by hxin** [comment]
the slow was caused by a 'rowwise' call on the DE result table(20k+ rows), which has been replaced now.
