### ISSUE TITLE
Check for choroid plexus contamination

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#225]
In [this project](https://github.com/sidbdri/rat_models_2023/blob/main/diff_expr_rat.R), we calculate an estimate of the per-sample amount of choroid plexus expression in the same way that we calculate mitochondrial expression proportion (choroid plexus tissue has a very different gene expression signature to other brain tissue, and is a common "contaminant" that can produce spurious D.E. results).

We could calculate this by default, and also plot it.

**Comment by hxin** [comment]
this is added as a separator plot atm, but can also be added into the existing MT plot, which will look like this:
<img width="963" alt="image" src="https://github.com/user-attachments/assets/ad73cb5e-ce63-4e7a-90dc-372fd7db5e65">

@lweasel

**Comment by lweasel** [comment]
Keep it as a separate plot for the moment I think.
