### ISSUE TITLE
Should we use an abundance cut-off for D. E. / GO analysis / GSEA ?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#23]
I think we should have a think at some point whether we might want to impose a minimum FPKM threshold, to try to avoid reporting D. E. genes / enrichment results that are probably not very biologically meaningful, and may just be the result of noise (e.g. FPKM < 0.5 probably equates to less than one actual transcript per-cell, so how likely are the genes to be having much real effect).

If we did this, we could either do it before even calculating the DESeq2 results, or do the differential expression analysis as standard, and then only consider genes with FPKM greater than the threshold in the GO and GSA analyses.

**Comment by hxin** [comment]
Agree. But is this FPKM an average FPKM across samples?  Do we have a similar parameter 'filter_low_counts' that remove genes that have more at least one count across samples? 
```
 if (filter_low_counts) {
    dds <- dds[rowSums(counts(dds)) > 1, ]
  }
```

**Comment by hxin** [comment]
I am doing the filter_by_comparison_avg_fpkm in the microglia project.

Should I refactor this into cookiecutter RE this issue?  @lweasel

**Comment by lweasel** [comment]
Hmm, let's leave this right now - I think that the general case for cookiecutter may need a bit more thought.
