### ISSUE TITLE
scipy numpy warning issue

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#26]
https://github.com/numpy/numpy/issues/11628

multiqc -d -f -m featureCounts -m star -m fastqc -m salmon -m kallisto -m sargasso /home/xinhe/projects/neurexin_splicing/results/mouse_rat
/home/xinhe/.virtualenvs/neurexin_splicing/local/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

**Comment by hxin** [comment]
This seems to be a harmless warning but I keep an issue here to come back later.

**Comment by lweasel** [comment]
Is this still happening, or can we close?
