### ISSUE TITLE
Improve manageability of rMATS results

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#28]
See sidbdri/als_neuron_correction_alternative_splicing#2 - any changes we make there should be incorporated in cookiecutter.

**Comment by hxin** [comment]
Done. However, the rMATS results still contain the AS events that have a level of difference smaller than what is specified. i.e, when setting Splicing_diff_cutoff to 0.1, there are still results containing AS event with a splicing difference smaller than 0.1. This seems to be a bug in the rMATS program, version 3.2.5 in specific. 

This could potentially be solved when the 4.0.2 version starts to support pairs analysis. Before that, however, we will just have to bear in mind that this might be a bug of the rMATS version we used.
