### ISSUE TITLE
Problem with Excel import of rMATS results spreadsheet 

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#31]
Is there any way that we could change the delimiter in the fields IJC_SAMPLE_1, SJC_SAMPLE_1, IJC_SAMPLE_2 and SJC_SAMPLE_2 from a comma to something else, e.g. a semi-colon? That would stop stupid Excel (sometimes) incorrectly interpreting those fields as very large numbers.

**Comment by hxin** [comment]
fixed in 184589d

**Comment by hxin** [comment]
tested in neurexin_splicing project. Now the result rmats table row looks like this:

ENSRNOG00000060496 | Kdm5d | Y | lysine demethylase 5D [Source:RGD   Symbol;Acc:2314436] | 100312983 | protein_coding | 5856 | 5615 | 5.12218161 | 451 | + | 573141 | 573430 | 573248 | 573430 | 572780 | 572975 | 0;0;2;3 | 0;3;5;45 | 0;0;0;6 | 0;1;2;74 | NA;0.0;0.167;0.032 | NA;0.0;0.0;0.039 | 0.053 | 1 | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
