### ISSUE TITLE
should we create qc/mappedread in the origin data folder so that we only need to do it once on the server?

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#38]

**Comment by lweasel** [comment]
Yes, we probably should (though it might have to be just for "current" projects, once space starts to become an issue on the server).

**Comment by hxin** [comment]
yes. I feel that this might also make the dev process easier, as most of the time, the error occurs after read_count...let's keep the thought here for a bit until we have time for the refactor.

**Comment by hxin** [comment]
for a follow-up project, could we clone the old container and work in it? Can we share the old result folder this way? just to note it here for future discussion.

**Comment by lweasel** [comment]
Thought about this a bit more, and I think I'm leaning towards "no" - I've got the feeling that separating the QC and mapped reads data from the provenance of the software versions and annotation files which which they were created is likely to create more problems than it's worth.
