### ISSUE TITLE
add gene check into QC

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#41]
I want to do this thus start an issue here.

Basically, we have a few difference marker genes that are expected to either expressing ONLY in certain cell type or highly xpressing in certain cell type. For example, the gene 'GFAP' as a marker gene in astrocyte.

This could be a simply QC step to find out potential contamination since we are doing it manually anyway. 

Tp workout a list of search genes for the cell types that we normally work with, i.e. neurons, astrocyte, microglia, we could use the http://www.brainrnaseq.org/ data? or just empirical lists from the biologist in the lab?

What do you think? @lweasel

**Comment by lweasel** [comment]
Good idea - and then plot graphs showing expression of those genes in all the samples presumably? I would probably suggest getting empirical lists from the biologists. Although it's useful, some of the data in http://www.brainrnaseq.org/ is a bit dodgy - for example the expression levels for neurons come from only one sample.

**Comment by hxin** [comment]
OK. will come back to this when we chat RE the infrastructure improvement
tasks

**Comment by lweasel** [comment]
gene == "ENSMUSG00000002111" | # Sfpi1 - microglia
         gene == "ENSMUSG00000024397" | # Aif1 - microglia
         gene == "ENSMUSG00000033006" | # Sox10 - oligodendrocyte
         gene == "ENSMUSG00000041607" | # Mbp - oligodendrocyte
         gene == "ENSMUSG00000031144" | # Syp - neuron
         gene == "ENSMUSG00000025576" | # Rbfox3 - neuron
         gene == "ENSMUSG00000024411" | # Aqp4 - astrocyte
         gene == "ENSMUSG00000020932")  # Gfap - astrocyte
