### ISSUE TITLE
find a way to condense the gsa result, currently producing too many files

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#44]
## possible implementation:
have a big csv file that contains all the genes as rows, all comparison details(l2fc, p,padj,raw_l2fc) + all enriched gene set as column.

**Comment by lweasel** [comment]
There is a version of this working in:

https://github.com/sidbdri/zoeb_anesthesia/blob/master/common_functions.R

We can see what people think before moving it into cookiecutter.
