### ISSUE TITLE
Update to latest versions of various tools used

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#51]
e.g. STAR, featureCounts, picard.

**Comment by lweasel** [comment]
STAR v2.6.1, featureCounts v1.6.3, bowtie2 v2.3.4.3, FastQC v0.11.8, kallisto v0.45.0, RSEM v1.3.1, salmon v0.12.0, sambamba v0.6.8

**Comment by hxin** [comment]
fixed in 94ed1dbdb64a3a7a10a831aec884fce5c753fbb2
