### ISSUE TITLE
Pass correct strandedness to picard CollectRnaSeqMetrics

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#54]
This has to be determined when running featureCounts, so we should move the picard execution to after that (which makes sense anyway, because it's very slow).

**Comment by hxin** [comment]
For picard:

STRAND=StrandSpecificity   
For strand-specific library prep. For unpaired reads, use FIRST_READ_TRANSCRIPTION_STRAND
if the reads are expected to be on the transcription strand.  Required. Possible values:
{NONE, FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND}   
                               
So the options(NONE, FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND) corresponding to 0,1,2 in featureCount, right?

Also, the postmodern data from Galatro indicated that samples can have different strand settings. Is this just an edge case? We are currently only using one sample and assume all others are the same.
@lweasel

**Comment by lweasel** [comment]
> So the options(NONE, FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND) corresponding to 0,1,2 in featureCount, right?

Yep, sounds right to me.

> Also, the postmodern data from Galatro indicated that samples can have different strand settings. Is this just an edge case? We are currently only using one sample and assume all others are the same.

I think that the Galatro data is going to be an edge case. I'd say let's keep it simple for the time being and assume that all samples have the same strandedness.

**Comment by hxin** [comment]
fixed in 2ae6ebf4026805624fee6e9b928cd32a2b920394
