### ISSUE TITLE
Download some Ensembl data into Docker containers?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#58]
We've probably discussed this before - but I spent quite a lot of time and mental effort yesterday trying and failing to reproduce some results (from the pre-Docker days) where I eventually worked out that the problem was that the information that we download into the genes.tsv files has changed from three years ago (unsurprisingly).

Thus when I recreated /srv/data/genome/mouse/ensembl-84, the genes.tsv file was different from when I originally created these results, and this caused the results to be different (in a very non-obvious way).

I wonder if - with files like these that might potentially change - we might download them into our containers as part of the project setup. We wouldn't need to do this with files that aren't likely to ever change, e.g. GTF files, STAR indexes for particular STAR versions etc.

**Comment by hxin** [comment]
Also move the picard data to download ensemble script, since this only needs to be done once.
