### ISSUE TITLE
A function to see the enrichment of particular term across comparisons

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#60]

**Comment by lweasel** [comment]
Would be great to have versions of this for both GO and GSA?

**Comment by hxin** [comment]
Yes. will look into this later

**Comment by hxin** [comment]
preliminary implementation of gsa result plot
![image](https://user-images.githubusercontent.com/3407502/53354216-3c00d380-391e-11e9-92e7-e7d7b3fd58ee.png)

**Comment by hxin** [comment]
slightly improve the plot layout.

![image](https://user-images.githubusercontent.com/3407502/53423881-189b5e80-39da-11e9-8e5f-3ec2b66059ca.png)

**Comment by lweasel** [comment]
Is this worth doing for GO results as well? (I'm thinking probably yes?).

**Comment by hxin** [comment]
done in 0a10a2f
