### ISSUE TITLE
Slight inconsistency in results folder structure

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#63]
Under the go/ and gsa/ folders, we have per-species sub-folders. But we don't have these species folders for the de_gene/ and reactome/ folders. Would it make sense to make this consistent - i.e. add species sub-folders to de_gene/ and reactome/ ?

**Comment by lweasel** [comment]
What do you think @hxin ?

**Comment by lweasel** [comment]
Another thing we could do make things more consistent - but also to make the results easier to scan through - is to have per-comparison sub-folders within the main "go" folder, just like we do for "gsa".

**Comment by hxin** [comment]
agree. Let's make them consistent. let's do it the gsa way for the go/reactome?

**Comment by lweasel** [comment]
Yes, sounds good.
