### ISSUE TITLE
xargs usage in run_analysis.sh

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#72]
There are a couple of pieces of code in run_analysis.sh marked with the comment "NEED TEST WHICH IS BETTER IN THE NEXT PROJECT". 

@hxin, do we know the answer to which is best now?

**Comment by hxin** [comment]
I think the xargs is working better my dummy 'checkBusy' function. I will remove this comment and replace the 'checkBusy' bit with the xagrs.
