### ISSUE TITLE
Strandedness setting in rMATS

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#76]
rMATS has a "libType" setting which we are currently setting to "fr-unstranded" (i.e. assuming that the RNA-seq data is unstranded). For stranded data we would need to manually change this.

If however, we recorded that strand information that we need to discover in order to run featureCounts (e.g. in a file), we could also use this to automatically use the correct setting for rMATS.

**Comment by hxin** [comment]
fixed in f20524c2b5acd8a71d49c8827477c3d51e651c54

**Comment by lweasel** [comment]
Duplicate issue.
