### ISSUE TITLE
rMATS: question about JC vs JCEC

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#81]
For our rMATS stats calculations, we use the reads from the "JC" files (i.e. "only reads that span splicing junctions") rather than the "JCEC" files (i.e. "reads that span splicing junctions and reads on target"). However I can't remember now whether we made a conscious decision about this?

The reason for asking is that there should be more JCEC reads than JC reads, so the stats might be a bit more reliable?

**Comment by hxin** [comment]
I think we had discussion RE this and chose to use JC over JCEC, but I cannot remember why we made that decision, on the top of my head. Let me see if I can find out.

**Comment by lweasel** [comment]
We cannot remember. Argh.
