### ISSUE TITLE
Check diff_expr_tx.R is working

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#84]
Can we just check that this transcript level D. E. script is functional next time we get some new data in.

**Comment by hxin** [comment]
I am 80% sure this will not work. I need a project to test this script and make necessary changes according to the non-tx script.  Do we have a new project coming soon? Otherwise, I can test it with an old one.

**Comment by lweasel** [comment]
Let's just check it out on the next set of new data.

**Comment by hxin** [comment]
fixed here. 8f63e82413f56f98c430052c238f1a029b217c6b

**Comment by lweasel** [comment]
Ok, I'm gonna assume this is working and check it in the next project (I think we should start running the tx level stuff by default anyway).
