### ISSUE TITLE
Bioconductor deprecated command

### ISSUE THREAD

**Issue by katieemelianova** [sidbdri/cookiecutter-de_analysis_skeleton#89]
Loading biocLite is done in the old way (pre R 3.6), and doesn't work in [load_packages.R](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/load_packages.R)

When commented out it seems to work anyway. When the updated way is used to install BiocManager, this requires admin access, so users without root access wouldn't be able to run anyway (I don't think).

Should we fix or remove?

**Comment by lweasel** [comment]
Yeah, in fact this was only there to print out the version of Bioconductor being used (which then ends up in a log file). I don't know if there is a recommended way to get the Bioconductor version now, and which doesn't require root access?

**Comment by lweasel** [comment]
(didn't mean to close!)

**Comment by lweasel** [comment]
Fixed in ec2e440eca6e911260de2f159da515c023e7b767.
