### ISSUE TITLE
featureCounts can count reads for all samples at the same time

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#9]
i.e. is there any good reason for this do be done in a loop as presently?

If not, the downstream differential expression script need to be changed to read in a file containing read counts for all genes.

**Comment by hxin** [comment]
This can be done by giving all the bam files as a parameter to the featurecount command. This does produce only a single file containing the feature count summary, with each column corresponding to one sample, however, is slower than running each sample in parallel. The featurecount seems limited the maximum number of cores to 64 and is doing internally one sample at a time. The parallelization may speed this process a lot, thus we decide to keep the current approach.

**Comment by hxin** [comment]
==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v1.5.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 2 BAM files                                      ||
||                           S /home/xinhe/projects/jpriller_microglia/re ... ||
||                           S /home/xinhe/projects/jpriller_microglia/re ... ||
||                                                                            ||
||             Output file : .counts_tmp                                      ||
||                 Summary : .counts_tmp.summary                              ||
||              Annotation : /home/xinhe/projects/jpriller_microglia/data ... ||
||      Dir for temp files : ./                                               ||
||                                                                            ||
||                 Threads : 16                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : counted                                          ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file /home/xinhe/projects/jpriller_microglia/data/mous ... ||
||    Features : 801623                                                       ||
||    Meta-features : 53801                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file /home/xinhe/projects/jpriller_microglia/results/mappe ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
