### ISSUE TITLE
detect_stranness bug in single species project

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#92]
This is a bug introduced when fixing #85. This bug is due to the different behaviour from the command 'grep'.

```bash 
> cd /tmp
> echo '1.greb.test' > 1.greb.test
> grep  'greb.test' *.greb.test

1.greb.test

> echo '2.greb.test' > 2.greb.test
> grep  'greb.test' *.greb.test

1.greb.test:1.greb.test
2.greb.test:2.greb.test

rm /tmp/*.greb.test
```

So when there are more than one files being returned by the command, it will show the file name for each file and the content. When there is only 1 file return, it will now show the file name. 

The detect_stranness code used the file name to find out the species information, thus will generate an error when there is only 1 file returned, i.e. in the single species project. 

This can be solve by adding the -H parameter:

```bash
-H, --with-filename       print the file name for each match
```

**Comment by katieemelianova** [comment]
Just tested this in a single species project and confirmed that this is happening, will do the fix now.

**Comment by hxin** [comment]
The code will NOT work when the sample name contains '.'
We need to either force the naming convention or have the code deal with it. 
It makes more sense to me to force the naming convention.  @katieemelianova @lweasel

**Comment by lweasel** [comment]
Fine with me.
