### ISSUE TITLE
Create gene_lengths.csv files when downloading from Ensembl?

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#95]
I'm not sure that there's any reason why we couldn't create the various `gene_lengths.csv` files for each species when we download data from Ensembl and create the directories in `/srv/data/genome`, rather than recreating this gene lengths files each time we run a new project - i.e. cookiecutter could just link to these files.

If we did this, we'd probably still need some backup code in cookiecutter for cases where the `gene_lengths.csv` files don't exist in the Ensembl directories.

@hxin @katieemelianova

**Comment by hxin** [comment]
I think we did move the genes.tsv to project because there was one project which you modified the genes.tsv from /srv/data/genome and was unable to re-recreate the result. I am not sure if this is why we also put the gene_lengths.csv in project folder rather then /srv/data/genome?

**Comment by lweasel** [comment]
I think gene_lengths.csv has always been in the project folder. But it's a good point, perhaps this needs a bit more thought.
